### ISSUE TITLE
Error parsing header, appears to be GATK annotation

### ISSUE THREAD

**Issue by rbutleriii** [rbutleriii/Clinotator#4]
In example vcf, the following error
```
INFO:root:Run date: 2019-02-21
INFO:root:Starting on example.vcf
CRITICAL:root: <class 'pandas.errors.ParserError'>. Error tokenizing data. C error: Expected 1 fields in line 141, saw 10
, line: 98
Traceback (most recent call last):
  File "/Users/rbutler/Github/Clinotator/clinotator/clinotator.py", line 193, in <module>
    main()
  File "/Users/rbutler/Github/Clinotator/clinotator/clinotator.py", line 188, in main
    output_files(vcf_tbl, variant_objects, outprefix)
  File "/Users/rbutler/Github/Clinotator/clinotator/clinotator.py", line 145, in output_files
    result_tbl = result_tbl[columnz]
  File "/Users/rbutler/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pandas/core/frame.py", line 2682, in __getitem__
    return self._getitem_array(key)
  File "/Users/rbutler/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pandas/core/frame.py", line 2726, in _getitem_array
    indexer = self.loc._convert_to_indexer(key, axis=1)
  File "/Users/rbutler/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pandas/core/indexing.py", line 1327, in _convert_to_indexer
    .format(mask=objarr[mask]))
KeyError: "['VID' 'CVVT' 'rsID' 'CVAL' 'vcfmatch' 'CVCS' 'CVSZ' 'CVNA' 'CVDS' 'CVLE'\n 'CTRS' 'CTAA' 'CTPS' 'CTRR'] not in index"
```
Looks like in a long log file, the header is not reading 5 lines, correctly (counting 135 instead of 140). Those lines are:
```
##GATKCommandLine.ApplyRecalibration=<>
##GATKCommandLine.GenotypeGVCFs=<>
##GATKCommandLine.HaplotypeCaller=<>
##GATKCommandLine.SelectVariants.2=<>
##GATKCommandLine.SelectVariants=<>
```
Probably the `.` in the Metainfo key.

**Comment by rbutleriii** [comment]
Yep, that is poor coding on the part of GATK. I updated the regex to compensate.
'''
<rant>
The "." character is a special character in dozens of languages and has particular meaning in vcf file format standards. Including it as part of a key variable is just terrible, and will likely cause problems downstream with common bioinformatics languages like python and R. It would have been much more convenient to use camelCase or an underscore (GATKCommandLine_ApplyRecalibration). Not the first time I have encountered sloppiness in GATK, and likely not the last.
</rant>
'''
